//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attendancesystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Absence
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public Nullable<System.DateTime> dateheure { get; set; }
        public Nullable<int> matiere_id { get; set; }
        public Nullable<int> eleve_id { get; set; }
    
        public virtual Eleve Eleve { get; set; }
        public virtual Matiere Matiere { get; set; }
    }
}
