//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attendancesystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iiteAttendanceEntities : DbContext
    {
        public iiteAttendanceEntities()
            : base("name=iiteAttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absence { get; set; }
        public virtual DbSet<Eleve> Eleve { get; set; }
        public virtual DbSet<Filiere> Filiere { get; set; }
        public virtual DbSet<Matiere> Matiere { get; set; }
        public virtual DbSet<Professeur> Professeur { get; set; }
    }
}
